/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marcelo ferrufino' at '8/25/15 8:21 AM' with Gradle 2.3
 *
 * @author marcelo ferrufino, @date 8/25/15 8:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
